algoritmo "Nome do Programa"

var
    reais, cotDollar, c: real
     dollares: inteiro

inicio
    c <- 1

    enquanto (c <= 4) faca
        escreva("Você irá fazer uma viagem para os EUA, me diga quanto você tem em real? ")
        leia(reais)
        cotDollar <- 5.58
        dollares <- reais / cotDollar
        escreval("Com a cotação do dollar hoje em ", cotDollar, ", seu dinheiro em dolár será de ", dollares, ".\n")
        c <- c + 1
    fimenquanto

fimalgoritmo