algoritmo "conversor"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

angulo, s: real

inicio

escreva("Informe um algulo: ")
leia(angulo)
s <- sen(grauprad(angulo))
escreval("O seno de ", angulo, " é igual a: ", s)

fimalgoritmo