algoritmo "Nome do Programa"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

a, b, c: inteiro

inicio

a <- 2
b <- 3
c <- 5
escreval(c>=a^b)
escreval(c<=a^b)
escreval(verdadeiro E verdadeiro)
escreval((c<a) ou (b<c))
escreval((c<a) e (b<c))
escreval(nao((c<a) e (b<c)))


fimalgoritmo